### ISSUE TITLE
why a fork?

### ISSUE THREAD

**Issue by ghost** [zyedidia/tcell#13]

**Comment by zyedidia** [comment]
There are a few features I wanted from tcell that the original doesn't provide, so I implemented them here. Namely: bracketed paste, events defined by custom escape sequences, sending escape sequences to the user, support for screen re-initialization on MacOS, and faster input from the tty (for example pasting megabytes of data is much faster). This fork is meant to be used by the micro editor (see https://github.com/zyedidia/micro).
