### ISSUE TITLE
Certain key combos, like ctrl+shift+<arrow> not recognized in foot

### ISSUE THREAD

**Issue by dnkl** [zyedidia/tcell#17]
It was brought to my attention that certain key combinations aren't recognized when running micro in [foot](https://codeberg.org/dnkl/foot).

Instead of triggering a key binding, the escape is printed in the terminal:

```
1 hello world[1;6D]
```

Examples of non-working key combinations:

* <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>arrow</kbd>
* <kbd>alt</kbd>+<kbd>arrow</kbd>
* <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>arrow</kbd>
* <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>home</kbd>.

<kbd>shift</kbd>+<kbd>arrow</kbd> works, as does <kbd>ctrl</kbd>+<kbd>arrow</kbd> and <kbd>ctrl</kbd>+<kbd>home</kbd>.

All of these work if I set `TERM=xterm-256color`, or even `TERM=alacritty`.

Foot's terminfo is **very** similar to xterm's. It does expose all the modifier combinations for e.g. <kbd>right</kbd>:
```sh
 infocmp -x1 foot|grep kRIT
        kRIT=\E[1;2C,
        kRIT3=\E[1;3C,
        kRIT4=\E[1;4C,
        kRIT5=\E[1;5C,
        kRIT6=\E[1;6C,
        kRIT7=\E[1;7C,
```
We can also look at the diff between `xterm-256color` and `foot`:
```sh
% infocmp -x1 xterm-256color foot
comparing xterm-256color to foot.
    comparing booleans.
        OTbs: T:F.
        mc5i: T:F.
    comparing numbers.
    comparing strings.
        flash: '\E[?5h$<100/>\E[?5l', '\E]555\E\\'.
        kbs: '^H', '^?'.
        kmous: '\E[<', '\E[M'.
        mc0: '\E[i', NULL.
        mc4: '\E[4i', NULL.
        mc5: '\E[5i', NULL.
        meml: '\El', NULL.
        memu: '\Em', NULL.
        mgc: '\E[?69l', NULL.
        oc: '\E]104\007', '\E]104\E\\'.
        rs1: '\Ec\E]104\007', '\Ec'.
        setab: '\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m', '\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48\:2\:5\:%p1%d%;m'.
        setaf: '\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m', '\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38\:2\:5\:%p1%d%;m'.
        smglr: '\E[?69h\E[%i%p1%d;%p2%ds', NULL.
        Cr: '\E]112\007', '\E]112\E\\'.
        Cs: '\E]12;%p1%s\007', '\E]12;%p1%s\E\\'.
        Ms: '\E]52;%p1%s;%p2%s\007', '\E]52;%p1%s;%p2%s\E\\'.
        Se: '\E[2 q', '\E[ q'.
        Sync: NULL, '\EP=%p1%ds\E\\'.
        XM: '\E[?1006;1000%?%p1%{1}%=%th%el%;', NULL.
        xm: '\E[<%i%p3%d;%p1%d;%p2%d;%?%p4%tM%em%;', NULL.
```
At least I cannot see anything in there that would/should/could make a difference here. But perhaps there is something in tcell's handling of "builtin" terminfos vs. external ones?

**Comment by CosmicToast** [comment]
I can reproduce the effect by setting `TERM` to `xterm-16color` (which is not built-in) and using xterm itself, proving this isn't a foot-specific problem.

**Comment by zyedidia** [comment]
Should be resolved now, let me know if it works. This might be worth opening an issue at gdamore/tcell.

**Comment by CosmicToast** [comment]
Latest micro built with tcell 2.0.3 segfaults.
Version output:
```
Version: 2.0.8-dev.6
Commit hash: 7ba48451
Compiled on September 14, 2020
```

I don't have the time to debug it right now, might have it later today or this week (in case it's needed).
Running with `TERM=xterm` (i.e a built-in terminfo) has it run just fine, so it's a related regression.

**Comment by zyedidia** [comment]
I looked into it and it should now be resolved. I also installed foot and tested there so hopefully this time I haven't missed anything. Thanks for your patience, and for reporting the issue!

**Comment by dnkl** [comment]
Works for me! Thanks!

**Comment by CosmicToast** [comment]
LGTM!
