### ISSUE TITLE
text selection

### ISSUE THREAD

**Issue by noroot777** [zyedidia/tcell#20]
Does this fork implement the text selection feature?
like issue: https://github.com/gdamore/tcell/issues/273

**Comment by zyedidia** [comment]
I'm not sure how this library could implement text selection. Mouse events are either sent by tcell to the application or they are not, depending on whether the mouse is enabled with the appropriate function call (enabling and disabling the mouse is supported). If mouse events are sent, the application should handle text selection, and if they are not, the terminal should handle it.
