### ISSUE TITLE
History/reason for this fork

### ISSUE THREAD

**Issue by Ttibsi** [zyedidia/tcell#24]
Hi, I found this through micro's go.mod  and I'm investigating the library right now -- is there any reason for this fork? It looks like from the diff that you're adding new features/fixing bugs -- but there's no plan to send those upstream? Should this fork be used for production over the main repo (despite the main repo having had more recent releases/commits, and is also still in development)?

**Comment by zyedidia** [comment]
There were a number of reasons for this fork. Off the top of my head: support for bracketed paste and OSC 52 and support for raw key sequence binding are the main two. There may have been performance reasons as well when the fork was originally made. At this point, I think the modifications to tcell here are quite micro-specific and I would recommend using the upstream version of tcell for other projects.

**Comment by Ttibsi** [comment]
Thank you for the rapid reply. That makes sense.
