### ISSUE TITLE
Sometimes scroll{up/down} events get interpeted as a button1 or button2 event.

### ISSUE THREAD

**Issue by CamilleScholtz** [zyedidia/tcell#3]
I don't know if this is a tcell or micro bug, anyways, I added a `messenger.Message(button)` line to all the cases in `switch button`. Scrolling up and down get interpreted as `256` and `512` respectively, however, when scrolling down and getting a `256`, and then moving the cursor it will actually send a `2`. When scrolling up, and then moving the cursor will send a `1`, which is really annoying, because it will activate a selection. This also happense when scrolling -> moving the cursor -> scrolling again (which can be seen in the webm I linked below)

Here is a webm of the the bug in action, look at the message bar for the button codes. (keep in mind I didn't press the left or middle button (aka `button1` and `button2`) once in this video, the part where it quickly switches between 1 and 2 is actually me just scrolling up and down): https://sr.ht/m_Rw.webm

in my opinion https://github.com/zyedidia/tcell/blob/master/tscreen.go#L870-L881 is most likely to somehow cause this issue, I have no idea though.

---

I just removed these lines https://github.com/zyedidia/tcell/blob/master/tscreen.go#L870-L881 entirely, and it still seems to happen, this makes me think it has something to do with motion.

---

https://github.com/zyedidia/tcell/pull/1 fixes the spawning of button1/2 events after scrolling, however, it also disables the button1/2 when clicking, so yeah...

---

I've been changing 100s of values in tscreen.go, but not luck fixing this issue as of yet. I think something in `parseXtermMouse()` is causing this. Changing:

``` go
        case 3:
            btn = int(b[i])
            state++
```

to

``` go
        case 3:
            btn = int(b[i]) - 32
            state++
```

Makes it spawn additional scroll events on motion after scrolling, instead of button1/2 events, so I think changing something in case 3 might fix this somehow...

**Comment by zyedidia** [comment]
I haven't been experiencing this issue on OSX with iTerm2. Maybe it is your terminal or system? You can see the exact raw events that the terminal is sending by installing termbox-go (`go get github.com/nsf/termbox-go`) and then running the demo `raw_input.go` (`go run $GOPATH/src/github.com/nsf/termbox-go/_demos/raw_input.go`).

**Comment by CamilleScholtz** [comment]
> Maybe it is your terminal or system?

Yeah it probably has something to do with rxvt-unicode, however I'd like to keep using  rxvt-unicode as my terminal :p. terminal application like vim and ncmpcpp don;t have this problem, so it must be fixable.

> You can see the exact raw events that the terminal is sending by installing termbox-go (go get github.com/nsf/termbox-go) and then running the demo raw_input.go (go run $GOPATH/src/github.com/nsf/termbox-go/_demos/raw_input.go).

Thanks, I'll try this.

**Comment by CamilleScholtz** [comment]
Here is a webm of the raw_input.go output: https://sr.ht/zdEI.webm

left click -> right click -> scrolling up and down -> motion
